### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by arnabau** [m0ppers/g14-perf-control#1]
Hi there!

I have zero knowledge of Rust, and I am trying to compile your code but I'm getting a lot of errors. My question: is there a method to run or install your program?

Thanks bro!

I am running Zorin 16 kernel 5.11

**Comment by m0ppers** [comment]
Interesting! I just retested it using the latest rust and I don't get any warnings or errors :thinking: having rust installed it usually involves just a simple `cargo build --release` and it should just work :unicorn: 

Anyway. I added a simple workflow that builds a binary and publishes it: https://github.com/m0ppers/g14-perf-control/releases

Closing for now :) Feel free to reopen if you still have problems

**Comment by arnabau** [comment]
Thanks for the answer bro!

I managed to compile the code and run the program, but I'm getting "Invalid Board. Are you using a G14?"

I am running Linux Zorin, kernel 5.11, run the program with sudo (without sudo I get the same error), the configuration file is in /etc/g14-perf-control.toml and I'm not using wayland.

Any idea?

**Comment by m0ppers** [comment]
Are the following paths present on your system?

/sys/devices/system/cpu/cpufreq/boost
/sys/devices/platform/asus-nb-wmi/throttle_thermal_policy

Which g14 do you have?

**Comment by arnabau** [comment]
Yes, both paths with root access (read/write). I can get info from those two files using ./g14-perf-control info so I guess it is reading them.

I have the G14 from the last year ryzen 7 gforce 1650

**Comment by m0ppers** [comment]
what is the content of /sys/class/dmi/id/board_name

and which version are you using (g14-perf-control --version). Background: I published 0.1.1 this morning because one of the rog libraries was updated to support more boards. Can you verify you are using 0.1.1?

**Comment by arnabau** [comment]
forget about it is working now!! 

I was using the binary that I compiled, for some reason it wasn't working. I did the test with the binary that you compiled and it works.

EDIT: "one of the rog libraries was updated" --> maybe that was the problem?

Many many thanks bro!
