### ISSUE TITLE
Not working in a fresh install

### ISSUE THREAD

**Issue by arnabau** [m0ppers/g14-perf-control#2]
Hello bro, This is very strange, the program was working just fine, but now does not work in a fresh Zorin installation, can change the profile but do not adjust the FAN values:

sudo ./g14-perf-control toggle
Fan profile: silent, Turbo: false
Error: Couldn't change profile

Caused by:
    0: failed to write to file No such file or directory (os error 2)
    1: No such file or directory (os error 2)

Everything have root access,
this file exist =>  /sys/devices/system/cpu/cpufreq/boost
this file exist => /sys/devices/platform/asus-nb-wmi/throttle_thermal_policy 
this file exist => /etc/g14-perf-control.toml

EDIT: the program manages to change the values within the files (boost and thermal policy), but I'm getting errors when it tries to change the fan curves: No such file or directory (os error 2)

Any idea?

Thanks in advance bro!

**Comment by m0ppers** [comment]
I have a guess: The curves are set using a library that is using the acpi call kernel module. Probably a fresh install is missing that kernel module. Does `/proc/acpi/call` exist on your system?

You will need to have this thing: https://github.com/mkottman/acpi_call (probably there is a package for your os)

**Comment by arnabau** [comment]
Thanks for the reply bro. I was thinking something like that, although I do not remember installing anything the previous time. In any case, and in case someone else needs it, I finally (was a little tricky) managed to install acpi-call-dkms 1.1.0 for ubuntu (I'm using Zorin 16) using zynaptics and load the module `/sbin/insmod acpi_call.ko`

Now is working again. 

Thanks bro!
